import {
  getAllInvoicesProcedure,
  getInvoiceByIdProcedure,
  confirmInvoiceProcedure,
  rejectInvoiceProcedure,
  updateItemMatchProcedure,
  retryInvoiceProcedure,
  manualEntryInvoiceProcedure,
  getInvoiceStatsProcedure,
  getFileUrlProcedure,
  getInvoiceConfigProcedure,
  updateInvoiceConfigProcedure,
  toggleOutOfStockProcedure,
  toggleItemTaxableProcedure,
  matchItemTaxRateProcedure,
  getSupplierAccuracyProcedure,
  updateInvoiceMatchProcedure,
  suggestOpenPOProcedure,
  checkDuplicateInvoiceNumberProcedure,
} from "../../controllers/invoiceController/index.ts"

import { t } from "../../trpc.ts"

export const invoiceRouter = t.router({
  getAll: getAllInvoicesProcedure,
  getById: getInvoiceByIdProcedure,
  confirm: confirmInvoiceProcedure,
  reject: rejectInvoiceProcedure,
  updateItemMatch: updateItemMatchProcedure,
  retry: retryInvoiceProcedure,
  manualEntry: manualEntryInvoiceProcedure,
  getStats: getInvoiceStatsProcedure,
  getFileUrl: getFileUrlProcedure,
  getConfig: getInvoiceConfigProcedure,
  updateConfig: updateInvoiceConfigProcedure,
  toggleOutOfStock: toggleOutOfStockProcedure,
  toggleItemTaxable: toggleItemTaxableProcedure,
  matchItemTaxRate: matchItemTaxRateProcedure,
  getSupplierAccuracy: getSupplierAccuracyProcedure,
  updateMatch: updateInvoiceMatchProcedure,
  suggestOpenPO: suggestOpenPOProcedure,
  checkDuplicates: checkDuplicateInvoiceNumberProcedure,
})
